### ISSUE TITLE
[PostgreSQL] Failed roles creation

### ISSUE THREAD

**Issue by hyvs** [manala/ansible-roles#123]
| | |
|-|-|
| Bug ?      | yes |
| Feature ?      | no |
| Role version  | 1.0.0 |
| OS  | Debian 8.9 |
| Init | systemd |

## Config 
```yaml
manala_postgresql_version: 9.4
manala_postgresql_config_template: config/default.dev.j2
manala_postgresql_config_hba_template: config/hba/default.dev.j2

manala_postgresql_roles:
  - role: app
    password:   ~
    attributes: ['SUPERUSER']
```

## Result 

```
TASK [manala.postgresql : requirements > Check if version is defined.] *********
skipping: [localhost]

TASK [manala.postgresql : install > Packages] **********************************
changed: [localhost] => (item=[u'postgresql-9.4', u'postgresql-contrib-9.4'])

TASK [manala.postgresql : config > PostgreSQL configuration] *******************
changed: [localhost]

TASK [manala.postgresql : config > PostgreSQL host-based authentication (hba) configuration] ***
changed: [localhost]

TASK [manala.postgresql : services > Ensure postgresql is running] *************
ok: [localhost] => (item=postgresql)

TASK [manala.postgresql : roles > Requirements] ********************************
ok: [localhost]

TASK [manala.postgresql : roles > Handle] **************************************
failed: [localhost] (item={u'attributes': [u'SUPERUSER'], u'password': None, u'role': u'app'}) =>
{
  "failed":true,
  "item":{
    "attributes":[
      "SUPERUSER"
    ],
    "password":null,
    "role":"app"
  },
  "msg":"unable to connect to database: fe_sendauth: no password supplied\n"
}
```
