### ISSUE TITLE
Wrong configuration template for influxdb ? 

### ISSUE THREAD

**Issue by glehnert** [manala/ansible-roles#16]
File : ansible-roles/manala.influxdb/templates/config/base.conf.j2

Issue : Configuration template seems to be wrong for : 
- line 393 : [[collectd]]
- line 428 : [[opentsdb]]

It seems that we have to remove the double [[ ]] to keep simple []

**Comment by hyvs** [comment]
Which version of influxdb did you use ? 

Double brackets seem right since https://github.com/influxdata/influxdb/commit/fccd0943a84ff7e50d9cd06baec771a2213cb695 and  https://github.com/influxdata/influxdb/commit/eec8cc94c794732933e3f8f7ecc0c9df3600eb80 (influxdb >= v0.13.0)

**Comment by glehnert** [comment]
That's why !  it's v0.10.0

**Comment by hyvs** [comment]
You can use a custom template to handle your 0.10.0 configuration :

```yaml
manala_influxdb_config_template: "{{ playbook_dir }}/templates/influxdb/conf_0.10.j2"
manala_influxdb_config:
  collectd-bind-address: :8089
```

`templates/influxdb/conf_0.10.j2`
```yaml
...
[collectd]
  enabled = true
  bind-address = "{{ item.config.collectd-bind-address }}"
...
```

For reference, you can found influxdb 0.10.3 config [here](https://github.com/influxdata/influxdb/blob/v0.10.3/etc/config.sample.toml)
