### ISSUE TITLE
[mysql] Always install python(3)-mysql

### ISSUE THREAD

**Issue by t2d** [manala/ansible-roles#316]
```
- name: install > Packages
  apt:
    name: "{{
      manala_mysql_install_packages|default(manala_mysql_install_packages_default, True)
      + (
        (manala_mysql_users|length > 0)
        or (manala_mysql_databases|length > 0)
        or (manala_mysql_replications|length > 0)
      )|ternary(
        ['python-mysqldb'],
        []
      )
    }}"
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
```

I want to configure databases in another role. This isn't possible, since I'll be missing `python(3)-mysql`.

In contrast, that's what `geerlingguy.mysql` does:
```
- name: Determine required MySQL Python libraries.
  set_fact:
    deb_mysql_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"

- name: Ensure MySQL Python libraries are installed.
  apt:
    name: "{{ deb_mysql_python_package }}"
    state: present
```

Would it be okay to copy this?
