### ISSUE TITLE
[apt] "'dict object' has no attribute u'bionic'"

### ISSUE THREAD

**Issue by apetitpa** [manala/ansible-roles#328]
Hi,

I'm facing an issue while using the manala.apt role on an Ubuntu 18.04 server.
The task `preferences > Templates presents` fails due to something I don't understand.
Here is the error `{"msg": "'dict object' has no attribute u'bionic'"}`

And here is how I used the role.
```
- hosts: web_server
  roles:
    - role: manala.apt
      vars:
        manala_apt_update: true
        manala_apt_repositories:
          - contrib
        manala_apt_preferences:
          - php@sury_php
          - nginx@nginx
```
I am on OSX with ansible version 2.7.10 and Python 3.6 on the host.

I tried to remove the `vars` and simply use `- role: manala.apt` with default values but got the same result.

Anyone has any clue about this ?

Thanks
