### ISSUE TITLE
Fail to determine latest version for role

### ISSUE THREAD

**Issue by jb-reynaud** [manala/ansible-roles#353]
On a new fresh install of a project with manala, I have a error an issue running `make setup`

```
TASK [manala.ansible-galaxy : roles > Install] ********************************
[...]
"ERROR!  Failed to determine latest version for role [manala.ansible-galaxy] - role not found
[...]
```
My `ansible.yml` config is
```yml
# App
- hosts: app
  gather_facts: true
  vars:
    manala_ansible_galaxy_roles:
      - manala.ansible-galaxy
      - manala.deploy
      - manala.skeleton
  roles:
    - manala.ansible-galaxy

# Global
- hosts: all
  gather_facts: true
  vars:
    manala_ansible_galaxy_roles_path: "{{ playbook_dir }}/roles"
    manala_ansible_galaxy_roles:
      - manala.ansible-galaxy
      - manala.deploy
  roles:
    - manala.ansible-galaxy
```

Any idea why it couldn't fin the role ? Thanks
