### ISSUE TITLE
blackfire role is failing (cannot start blackfire-agent)

### ISSUE THREAD

**Issue by tristanbes** [manala/ansible-roles#99]
Hello,

After passing the right variable:

```
app_local_patterns:
  apt_repositories:
    - blackfire

  php_blackfire: false

  php_blackfire_agent:
    - server-id:  xxxx
    - server-token: xxxx
  php_blackfire_client:
    - client-id:  xxxx
    - client-token: xxxx
```

The blackfire agent is installed as reported when running `make provision` BUT it fails when it tries to start the service (or restart).

Solution was to connect to VM, use `blackfire-agent register` to manually insert the token and server id.

And after doing so, re-run the `make provision`
